#9) გაიხსენეთ ლოგიკური ოპერატორი და ჩამოწერეთ ყველა კომბინაცია რაც საჭიროა (სულ უნდა იყოს რვა, გაიხსენეთ ნასწავლიდან)

print(False and False)
print(False and True)
print(True and False)
print(True and True)
print(False or False)
print(False or True)
print(True or False)
print(True or True)